sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t arashshirani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arashshirani/docker-react yarn test
